AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - bin/*
    - script/*
    - db/migrate/*.rb
    - db/schema.rb
  RunRailsCops: true

# Remove when upgrading to Rails 4.x
Rails/ActionFilter:
  Enabled: false

LineLength:
  Max: 120

Documentation:
  Enabled: false

RegexpLiteral:
  MaxSlashes: 0

FileName:
  Exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
