development:
  adapter: postgresql
  database: dianewillis-devel
  username: docwhat
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: dianewillis-test
  username: docwhat
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dianewillis
  username: docwhat
  pool: 5
  timeout: 5000
